# Banyan — dev tasks. See `make help`.
# The .xcodeproj is generated by XcodeGen from project.yml and is gitignored,
# so most targets depend on `generate`.

SCHEME    := Banyan
BUNDLE_ID := com.aryandas.Banyan
SIM       := iPhone 17
DEST      := platform=iOS Simulator,name=$(SIM)
PROJECT   := Banyan.xcodeproj

# App bundle path inside DerivedData, resolved lazily (only when a target needs it).
APP = $(shell find $(HOME)/Library/Developer/Xcode/DerivedData/Banyan-*/Build/Products/Debug-iphonesimulator -name "Banyan.app" -maxdepth 1 2>/dev/null | head -1)

# Optional test filter: `make test T=LinkUnlinkTests` or `make test T=LinkUnlinkTests/unlinkRemovesConnection`
ONLY := $(if $(T),-only-testing:BanyanTests/$(T),)

.DEFAULT_GOAL := help

## help: list the available targets
.PHONY: help
help:
	@grep -E '^## ' $(MAKEFILE_LIST) | sed 's/## //' | awk -F': ' '{printf "  \033[36m%-12s\033[0m %s\n", $$1, $$2}'

## generate: regenerate Banyan.xcodeproj from project.yml (run after adding/removing files)
.PHONY: generate
generate:
	xcodegen generate

## build: generate + build for the simulator
.PHONY: build
build: generate
	xcodebuild -scheme $(SCHEME) -sdk iphonesimulator -destination '$(DEST)' build

## test: run tests. All by default; `make test T=SuiteName[/testName]` to filter
.PHONY: test
test: generate
	xcodebuild test -scheme $(SCHEME) -sdk iphonesimulator -destination '$(DEST)' $(ONLY)

## boot: boot the simulator (no-op if already booted)
.PHONY: boot
boot:
	xcrun simctl bootstatus "$(SIM)" -b

## run: build, install onto the booted simulator, and launch
.PHONY: run
run: build boot
	xcrun simctl install "$(SIM)" "$(APP)"
	xcrun simctl launch "$(SIM)" $(BUNDLE_ID)

## sim: open the Simulator app window
.PHONY: sim
sim:
	open -a Simulator

## shot: screenshot the simulator (OUT=path.png, default ./banyan.png)
.PHONY: shot
shot:
	xcrun simctl io "$(SIM)" screenshot $(if $(OUT),$(OUT),banyan.png)

## reset: terminate + uninstall to clear stored data (back to the Welcome screen)
.PHONY: reset
reset:
	-xcrun simctl terminate "$(SIM)" $(BUNDLE_ID)
	-xcrun simctl uninstall "$(SIM)" $(BUNDLE_ID)

## clean: reset the app and delete Banyan's DerivedData
.PHONY: clean
clean: reset
	-rm -rf $(HOME)/Library/Developer/Xcode/DerivedData/Banyan-*
